insert into users (email, password, active)
values
--     admin 1-4
    ('tomek@gmail.com', '$2a$12$TzIHka.M2r597FjIgAnMGOhDQ0cFllQaUP71quBbK8W8fizrhFxBy', true),
    ('paulina321@interia.pl', '$2a$12$wsezP0.lG4bC5mq4JsNa0esrGM5BaE/RvAVf37lTpUa4ll/8nJo82', true),
    ('piotrw@wp.pl', '$2a$12$Wox3ZqdWCfRCYHKJC9j9gu4hrtmbi1dyLDQhLW2l/A2wgzHYSpLXi', true),
    ('raf654@onet.pl', '$2a$12$jtBOzctNQhzFgWvUbFH6DeqQFOZ4GDFxJmdi0UeD00Q7h9xQPRWTS', true),
-- patients 5-14
    ('sberrey0@ftc.gov', '$2a$12$5AIxjPpLmDg4lnEIZY20wuBpvC9Fcw1V7XBcH0ZoIbYZ4J2jnxdKS', true),
    ('tkingaby1@vkontakte.ru', '$2a$04$L4ytMVXRckC5E/O4.gLP.uC9J58Sr8Pt7wblHki8AuasUqoMtCanq', true),
    ('ladcock2@typepad.com', '$2a$04$VBqjGGOu9Us/OjMEZcufvOLycizHUoKJzzQRbPCkLvx60b7lL3yJO', true),
    ('jrittmeier3@nbcnews.com', '$2a$04$KY3pibnuTDS2tBWnQX39eugy9hdLDccFT2YW4e2FsEKUH8CVC2QhO', true),
    ('dkirvell4@123-reg.co.uk', '$2a$04$JTEIcsTftgXjwcCvKZoyluRF4GvSpgric6xuAc00taDVPffmHx./q', true),
    ('iorrah5@economist.com', '$2a$04$gJqMMCVK2iWxRpREmeltp.Yog06gIz1QJIgYQJR5Z5VyEd/FfT0om', true),
    ('etruckell6@cisco.com', '$2a$04$Rlbe2MIw/589HuWuiyzJ/.Q8sxBn6hanJ1qV8B0WhdTBdD41uPfIO', true),
    ('gbricksey7@noaa.gov', '$2a$04$jcBAXOE2GAM6GPRcVsmv9u8h9znax76TbIHfWdrXB/gy9d27g3ONq', true),
    ('bkeoghan8@t.co', '$2a$04$ywdMIzDHXBYyv1e.xo0cb.9i6b2X3Ii6IMnTkVo1JA.iFnQRXBA.6', true),
    ('dfrankema9@noaa.gov', '$2a$04$62x8oxFS6/kBVlViR8nHv..zk1SRQViB0vuIALXXP/MBgudQIBxFa', true),
-- doctors 15-24
    ('bneles0@amazon.de', '$2a$12$4Eu2CYQUI8yFWv8xptVTPOdsflslqyOx1QS9ovHJmZZbJhr98ouOO', true),
    ('dgingell1@japanpost.jp', '$2a$04$0c494FoHg7nxolQ7xqA80e8iHvebfJ4vQgF/6GLGcZmKY7ey8VY/O', true),
    ('kbyrd2@statcounter.com', '$2a$04$X4T6WQA0ehKUt9x.E1RAUeUfp1JkPGojwOV6O/NyB9LCdA31SQuaa', true),
    ('cdumbarton3@wikimedia.org', '$2a$04$QYP8YW1eGxr3rbeg2aNXguUM6fQ8azW/DhDZZcURKUh7/ncjA6ms.', true),
    ('rkryszka4@reference.com', '$2a$04$xG6j0eRIi8FB7uSRY39P1e4IltjRCSdvkHxugsy6zGJDagi/RfGtC', true),
    ('bhumpherston5@businessweek.com', '$2a$04$qvfp5wSL04Ld9C1uVxLpS.oNyLNeR1VwCkKUqq5G5ZTuoflrCnKYu', true),
    ('hoboy6@examiner.com', '$2a$04$xCKZz8JzZH0HwiKJ7r8/IejINe7uTsMfONrKiijQRCJgHHIBn.SZ.', true),
    ('ntolossi7@artisteer.com', '$2a$04$XHAACwsJCOok93VgQaHv5Os7CDLL.tr/Ftw3PMtzEDAW9ZPFYe4gm', true),
    ('rvautin8@webeden.co.uk', '$2a$04$3ZI3g1fX6ZBkRyVUCn0N7.WLpX/QpFSC3CiNysggzxNyHtS9.96gC', true),
    ('rtruce9@tuttocitta.it', '$2a$04$x/ejbl0TQw67gNLoW8eznOTsr9JdBCkgXWGNS27TUgSgjwZAynfFu', true);

insert into role (role)
values
    ('ADMIN'),
    ('PATIENT'),
    ('DOCTOR');

insert into user_role (user_id, role_id)
values
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 1),
    (2, 2),
    (2, 3),
    (3, 1),
    (3, 2),
    (3, 3),
    (4, 1),
    (4, 2),
    (4, 3),
    (5, 2),
    (6, 2),
    (7, 2),
    (8, 2),
    (9, 2),
    (10, 2),
    (11, 2),
    (12, 2),
    (13, 2),
    (14, 2),
    (15, 3),
    (16, 3),
    (17, 3),
    (18, 3),
    (19, 3),
    (20, 3),
    (21, 3),
    (22, 3),
    (23, 3),
    (24, 3);

insert into admin (first_name, last_name, pesel, user_id)
values
    ('Tomek', 'Kowalsky', '47231754321', 1),
    ('Paulina', 'Dolna', '98324534567', 2),
    ('Piotr', 'Nowak', '88325645678', 3),
    ('Szymon', 'Niski', '73674395678', 4);

insert into specialization (name, visit_time)
values
 ('Cardiology', '00:30:00'),
 ('Neurology', '01:00:00'),
 ('Orthopedics', '00:30:00'),
 ('Dermatology', '00:15:00'),
 ('Psychiatry', '00:30:00');

insert into patient (first_name, last_name, pesel, phone, user_id)
values
 ('Shellysheldon', 'Berrey', '54678734567', '504 728 6473', 5),
 ('Thorpe', 'Kingaby', '74234578976', '887 209 2673', 6),
 ('Leoline', 'Adcock', '68765486789', '121 286 8970', 7),
 ('Justus', 'Rittmeier', '71234565376', '525 335 3617', 8),
 ('Dominga', 'Kirvell', '89763467854', '162 816 0313', 9),
 ('Igor', 'Orrah', '57651234589', '956 198 9981', 10),
 ('Ellynn', 'Truckell', '65476512568', '171 955 3373', 11),
 ('Gabrila', 'Bricksey', '80764576587', '253 244 5476', 12),
 ('Burty', 'Keoghan', '67537689709', '465 511 0602', 13),
 ('Daveta', 'Frankema', '56432656789', '478 801 5601', 14);


insert into doctor (first_name, last_name, pesel, user_id, specialization_id)
values
 ('Bald', 'Neles', '45675434567', 15, 1),
 ('Dick', 'Gingell', '84698723485', 16, 2),
 ('Kellby', 'Byrd', '68652134098', 17, 3),
 ('Corine', 'Dumbarton', '51237689076', 18, 4),
 ('Ramona', 'Kryszka', '98764532145', 19, 2),
 ('Barbee', 'Humpherston', '58763465432', 20, 5),
 ('Harv', 'Oboy', '97653476487', 21, 3),
 ('Nadean', 'Tolossi', '32765476521', 22, 1),
 ('Rica', 'Vautin', '65478423476', 23, 5),
 ('Ralf', 'Truce', '67896545689', 24, 4);

insert into appointment (date, start_time, end_time, doctor_id, patient_id, cancelled, notes)
values
 ('2023-09-22', '8:30', '9:00', 3, 8, false, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien'),
 ('2023-10-13', '11:00', '11:30', 9, 9, false, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit'),
 ('2023-10-21', '12:30', '13:30', 5, 4, false, 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus'),
 ('2023-09-22', '10:30', '10:45', 10, 1, false, 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
 ('2023-10-12', '15:30', '16:00', 6, 6, false, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut'),
 ('2023-09-05', '16:30', '17:00', 5, 5, false, 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero'),
 ('2023-10-05', '16:00', '16:30', 9, 2, true, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus'),
 ('2023-09-28', '16:15', '16:45', 2, 4, false, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non'),
 ('2023-09-18', '12:30', '13:00', 9, 1, true, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat'),
 ('2023-09-21', '8:00', '8:30', 5, 8, false, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia'),
 ('2023-10-10', '14:30', '15:00', 5, 6, false, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus'),
 ('2023-10-01', '8:00', '8:30', 9, 3, false, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam'),
 ('2023-09-08', '13:15', '14:15', 8, 2, true, 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien'),
 ('2023-09-02', '12:15', '12:30', 10, 9, false, 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc'),
 ('2023-09-23', '11:45', '12:00', 4, 2, false, 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque'),
 ('2023-10-21', '8:30', '9:00', 4, 1, false, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc'),
 ('2023-10-01', '10:00', '10:30', 8, 8, false, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero'),
 ('2023-09-01', '12:30', '13:00', 4, 2, false, 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non'),
 ('2023-10-17', '17:45', '18:00', 8, 10, true, 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh'),
 ('2023-09-10', '15:00', '15:30', 10, 1, false, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat'),
 ('2023-09-07', '17:15', '17:45', 2, 8, false, 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi'),
 ('2023-09-09', '14:45', '15:45', 6, 6, true, 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti'),
 ('2023-09-20', '16:30', '17:00', 8, 7, false, 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer'),
 ('2023-10-27', '17:45', '18:15', 6, 1, false, 'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui'),
 ('2023-09-28', '17:30', '18:00', 5, 10, false, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla'),
 ('2023-09-04', '14:00', '14:30', 4, 6, false, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel'),
 ('2023-09-06', '11:45', '12:15', 4, 7, false, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum'),
 ('2023-10-27', '12:45', '13:00', 9, 7, false, 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget'),
 ('2023-09-27', '15:45', '16:45', 1, 1, false, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra'),
 ('2023-10-04', '8:45', '9:15', 2, 9, false, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae'),
 ('2023-09-14', '15:00', '15:30', 4, 2, true, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo'),
 ('2023-10-19', '16:30', '17:00', 3, 4, false, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est'),
 ('2023-10-02', '17:45', '18:00', 4, 2, false, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi'),
 ('2023-10-29', '10:00', '10:30', 6, 2, false, 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum'),
 ('2023-10-01', '9:45', '10:45', 2, 2, false, 'congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse'),
 ('2023-09-30', '17:00', '17:30', 5, 3, false, 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec'),
 ('2023-10-06', '12:00', '12:30', 5, 9, true, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere'),
 ('2023-09-04', '16:15', '16:45', 5, 2, false, 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id'),
 ('2023-10-17', '13:30', '14:00', 4, 1, false, 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium'),
 ('2023-09-07', '12:45', '13:00', 10, 7, false, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla'),
 ('2023-10-03', '9:30', '10:30', 1, 10, false, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem'),
 ('2023-10-22', '10:30', '11:00', 9, 1, false, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus'),
 ('2023-09-01', '15:45', '16:15', 3, 3, false, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam'),
 ('2023-10-27', '14:45', '15:15', 1, 8, false, 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam'),
 ('2023-09-03', '8:45', '9:15', 5, 2, false, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum'),
 ('2023-10-10', '12:45', '13:15', 7, 5, false, 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit'),
 ('2023-10-17', '11:30', '12:00', 10, 2, false, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo'),
 ('2023-09-28', '11:00', '11:30', 1, 4, true, 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare'),
 ('2023-10-05', '16:45', '17:00', 9, 3, false, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin'),
 ('2023-10-16', '9:00', '10:00', 4, 2, false, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel'),
 ('2023-10-07', '8:00', '8:30', 7, 3, false, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt'),
 ('2023-10-22', '9:30', '10:00', 3, 5, false, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non'),
 ('2023-09-30', '8:30', '9:00', 7, 1, false, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea'),
 ('2023-10-23', '15:00', '16:00', 7, 2, false, 'non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac'),
 ('2023-09-28', '16:15', '16:45', 6, 1, false, 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at'),
 ('2023-09-19', '15:45', '16:15', 2, 4, true, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce'),
 ('2023-10-27', '16:15', '16:45', 1, 4, false, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus'),
 ('2023-09-24', '12:45', '13:15', 2, 6, false, 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc'),
 ('2023-10-16', '14:15', '14:45', 4, 2, false, 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien'),
 ('2023-09-04', '16:00', '17:00', 3, 7, false, 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis'),
 ('2023-10-17', '16:00', '16:15', 7, 8, false, 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque'),
 ('2023-10-26', '17:45', '18:15', 5, 1, false, 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea'),
 ('2023-10-15', '8:30', '9:00', 3, 5, false, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede'),
 ('2023-10-08', '10:45', '11:15', 8, 9, true, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede'),
 ('2023-10-03', '11:45', '12:15', 3, 10, false, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt'),
 ('2023-10-04', '15:45', '16:00', 3, 1, true, 'mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales'),
 ('2023-09-29', '10:45', '11:15', 1, 8, false, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien'),
 ('2023-10-16', '12:15', '12:45', 7, 6, false, 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue'),
 ('2023-09-03', '15:30', '16:00', 2, 6, false, 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac'),
 ('2023-10-15', '11:30', '12:00', 6, 3, false, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus'),
 ('2023-10-20', '12:30', '13:00', 9, 6, false, 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus'),
 ('2023-10-28', '12:45', '13:00', 4, 3, true, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero'),
 ('2023-09-16', '8:15', '8:45', 3, 8, false, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis'),
 ('2023-10-22', '13:30', '14:00', 8, 6, false, 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis'),
 ('2023-10-12', '17:30', '18:00', 1, 1, false, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget'),
 ('2023-10-18', '15:45', '16:15', 5, 2, true, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
 ('2023-09-18', '9:45', '10:45', 9, 2, false, 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse'),
 ('2023-09-19', '12:00', '12:30', 7, 6, false, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus'),
 ('2023-10-30', '14:45', '15:00', 10, 7, false, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh'),
 ('2023-09-18', '9:45', '10:15', 10, 4, false, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat'),
 ('2023-09-11', '8:30', '9:30', 2, 6, false, 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor'),
 ('2023-09-07', '16:00', '16:30', 1, 2, false, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus'),
 ('2023-10-01', '8:30', '9:00', 3, 1, false, 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum'),
 ('2023-09-02', '9:30', '10:00', 8, 10, true, 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh'),
 ('2023-09-24', '14:30', '15:00', 7, 2, false, 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices'),
 ('2023-09-08', '8:15', '8:45', 2, 1, false, 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet'),
 ('2023-09-15', '9:30', '10:00', 1, 6, false, 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor'),
 ('2023-09-11', '10:45', '11:15', 1, 3, false, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede'),
 ('2023-09-08', '10:30', '11:00', 7, 1, false, 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient'),
 ('2023-09-01', '14:00', '14:30', 3, 9, false, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices'),
 ('2023-09-27', '11:00', '11:30', 4, 9, false, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl'),
 ('2023-10-10', '14:30', '14:45', 2, 8, false, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue'),
 ('2023-09-19', '10:00', '10:30', 8, 3, false, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed'),
 ('2023-10-20', '14:45', '15:45', 7, 4, false, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede'),
 ('2023-10-24', '15:15', '15:30', 9, 2, false, 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque'),
 ('2023-09-24', '13:00', '13:30', 5, 6, false, 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis'),
 ('2023-09-13', '9:45', '10:00', 6, 7, false, 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum'),
 ('2023-09-04', '10:30', '11:00', 5, 1, false, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at'),
 ('2023-10-24', '10:15', '10:45', 2, 6, false, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl'),
 ('2023-10-05', '9:45', '10:15', 2, 5, false, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas'),
 ('2023-10-13', '10:45', '11:00', 9, 7, false, 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi'),
 ('2023-10-28', '17:45', '18:15', 2, 1, false, 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor'),
 ('2023-10-18', '10:45', '11:15', 5, 3, false, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede'),
 ('2023-10-27', '17:30', '18:00', 5, 7, false, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse'),
 ('2023-10-20', '15:30', '16:00', 1, 8, false, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum'),
 ('2023-09-29', '16:30', '17:00', 8, 9, false, 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac'),
 ('2023-09-20', '12:45', '13:45', 3, 10, true, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque'),
 ('2023-10-26', '9:30', '10:00', 4, 4, false, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
 ('2023-10-08', '11:00', '11:15', 9, 6, false, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est'),
 ('2023-10-05', '13:45', '14:00', 1, 3, false, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum'),
 ('2023-09-29', '12:30', '13:00', 2, 4, false, 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum'),
 ('2023-10-15', '10:15', '10:45', 2, 5, false, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo'),
 ('2023-09-27', '15:00', '16:00', 4, 6, false, 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum'),
 ('2023-10-08', '15:30', '16:00', 6, 1, false, 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in'),
 ('2023-09-24', '12:45', '13:00', 1, 4, false, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes'),
 ('2023-09-07', '8:00', '8:30', 4, 9, false, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum'),
 ('2023-10-25', '17:00', '17:15', 8, 6, false, 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst'),
 ('2023-10-27', '13:45', '14:00', 2, 10, false, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut'),
 ('2023-09-08', '10:30', '11:00', 3, 6, false, 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis'),
 ('2023-09-29', '17:30', '18:30', 7, 7, false, 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque'),
 ('2023-09-27', '8:30', '8:45', 4, 1, false, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis'),
 ('2023-09-23', '13:00', '13:30', 2, 8, false, 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh'),
 ('2023-10-30', '13:45', '14:15', 9, 1, true, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan'),
 ('2023-09-05', '8:15', '8:30', 4, 6, false, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi'),
 ('2023-09-19', '15:45', '16:15', 1, 5, false, 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas'),
 ('2023-09-01', '13:30', '14:00', 9, 2, true, 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec'),
 ('2023-09-19', '17:15', '17:45', 7, 2, false, 'congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient'),
 ('2023-09-23', '10:45', '11:15', 4, 1, false, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac'),
 ('2023-10-20', '12:00', '12:30', 4, 1, false, 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum'),
 ('2023-10-05', '17:00', '17:30', 1, 3, false, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis'),
 ('2023-10-23', '16:30', '17:00', 10, 5, true, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula'),
 ('2023-10-15', '16:30', '16:45', 1, 7, false, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum'),
 ('2023-09-08', '10:45', '11:15', 7, 5, true, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
 ('2023-10-21', '17:30', '18:00', 5, 3, false, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit'),
 ('2023-10-24', '13:45', '14:00', 4, 10, false, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo'),
 ('2023-09-03', '11:15', '12:15', 8, 1, false, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
 ('2023-09-01', '15:00', '16:00', 7, 2, false, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam'),
 ('2023-09-01', '11:45', '12:00', 9, 8, false, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a'),
 ('2023-09-06', '8:30', '9:00', 10, 8, true, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede'),
 ('2023-10-22', '15:00', '15:30', 4, 7, false, 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum'),
 ('2023-10-18', '9:30', '10:00', 10, 7, false, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi'),
 ('2023-09-18', '8:45', '9:00', 5, 4, false, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis'),
 ('2023-10-23', '17:30', '18:00', 6, 2, false, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae'),
 ('2023-10-18', '10:30', '11:00', 10, 3, true, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis'),
 ('2023-10-16', '12:30', '13:30', 5, 2, false, 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem'),
 ('2023-09-21', '14:00', '15:00', 7, 1, false, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut'),
 ('2023-09-05', '13:45', '14:00', 2, 2, true, 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non'),
 ('2023-10-07', '8:45', '9:00', 9, 4, false, 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae'),
 ('2023-10-13', '15:45', '16:45', 9, 1, false, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis'),
 ('2023-10-08', '17:30', '18:00', 2, 2, false, 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices');

insert into doctor_schedule (doctor_id, start_hour, end_hour, date)
values
 (1, '19:30', '20:00', '2023-09-29'),
 (2, '15:00', '16:00', '2023-10-16'),
 (3, '8:00', '8:30', '2023-9-17'),
 (4, '10:30', '10:45', '2023-09-17'),
 (5, '11:15', '11:45', '2023-10-05'),
 (7, '15:15', '16:15', '2023-10-08'),
 (8, '15:45', '16:00', '2023-09-29'),
 (2, '15:00', '15:30', '2023-10-01'),
 (4, '8:45', '9:00', '2023-09-16'),
 (9, '11:30', '12:00', '2023-09-07'),
 (10, '13:30', '13:45', '2023-10-23'),
 (6, '9:45', '10:15', '2023-09-04'),
 (5, '16:15', '16:45', '2023-10-27'),
 (1, '11:30', '12:00', '2023-10-03'),
 (2, '19:00', '20:00', '2023-09-28'),
 (4, '11:15', '12:15', '2023-09-08'),
 (7, '17:30', '18:00', '2023-10-10'),
 (3, '10:30', '11:00', '2023-09-15'),
 (8, '19:15', '19:45', '2023-09-18'),
 (9, '16:45', '17:00', '2023-10-04'),
 (10, '10:30', '10:45', '2023-10-06'),
 (2, '11:00', '12:00', '2023-10-23'),
 (3, '10:00', '10:15', '2023-09-20'),
 (6, '8:45', '9:15', '2023-09-12'),
 (5, '14:30', '15:30', '2023-10-06'),
 (9, '19:00', '19:30', '2023-10-29'),
 (8, '15:00', '15:30', '2023-09-13'),
 (2, '14:15', '15:15', '2023-09-30'),
 (3, '15:00', '15:30', '2023-10-07'),
 (7, '14:45', '15:45', '2023-10-06'),
 (8, '19:30', '20:00', '2023-09-30'),
 (4, '15:00', '15:30', '2023-09-30'),
 (6, '8:00', '8:30', '2023-10-30'),
 (10, '10:30', '11:00', '2023-10-30'),
 (5, '11:00', '11:30', '2023-10-30'),
 (2, '15:30', '16:00', '2023-10-30'),
 (7, '15:30', '16:00', '2023-09-30'),
 (8, '15:00', '15:30', '2023-09-30'),
 (4, '8:30', '9:00', '2023-09-30'),
 (2, '8:30', '9:00', '2023-10-30'),
 (1, '10:30', '11:00', '2023-10-30'),
 (4, '16:00', '16:30', '2023-10-30'),
 (9, '08:00', '08:30', '2023-09-29'),
 (6, '08:30', '09:00', '2023-09-29'),
 (3, '09:00', '09:30', '2023-09-29'),
 (7, '09:30', '10:00', '2023-09-29'),
 (8, '10:00', '10:30', '2023-09-29'),
 (10, '08:00', '08:30', '2023-09-28'),
 (9, '08:30', '09:00', '2023-09-28'),
 (6, '09:00', '09:30', '2023-10-01'),
 (2, '09:30', '10:00', '2023-10-01'),
 (3, '10:00', '10:30', '2023-10-02'),
 (4, '10:30', '11:00', '2023-10-02'),
 (7, '11:00', '11:30', '2023-09-28'),
 (5, '11:30', '12:00', '2023-09-28'),
 (9, '12:00', '12:30', '2023-09-28'),
 (6, '12:30', '13:00', '2023-09-28'),
 (4, '13:00', '13:30', '2023-10-01'),
 (8, '13:30', '14:00', '2023-10-01'),
 (9, '14:00', '14:30', '2023-10-01'),
 (5, '14:30', '15:00', '2023-10-02'),
 (6, '15:00', '15:30', '2023-10-02'),
 (10, '15:30', '16:00', '2023-10-02'),
 (2, '16:00', '16:30', '2023-10-03'),
 (1, '16:30', '17:00', '2023-10-03'),
 (3, '17:00', '17:30', '2023-10-03');